# Generated by Django 5.0.4 on 2024-10-03 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_usertype_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfoUser',
            new_name='UserInfo',
        ),
    ]
