# Generated by Django 5.0.4 on 2024-10-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_userinfouser_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person_name', models.CharField(max_length=255)),
                ('hotel_name', models.CharField(max_length=255)),
                ('address_location', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('google_map_address', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
