# Generated by Django 5.0.4 on 2024-10-04 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_email_address_hotelowner_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelowner',
            name='address_location',
            field=models.CharField(max_length=255),
        ),
    ]
