# Generated by Django 5.0.4 on 2024-10-04 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_hotelowner_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelowner',
            name='user',
        ),
    ]
