# Generated by Django 5.0.4 on 2024-10-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_hotelowner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelowner',
            name='token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
