# Generated by Django 5.0.4 on 2024-10-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_hotelowner_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelowner',
            name='token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
