# Generated by Django 5.0.4 on 2024-10-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_hotelowner_token_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentmenus',
            name='menu_url',
            field=models.CharField(max_length=255),
        ),
    ]
