# Generated by Django 5.0.4 on 2024-10-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_parentmenus_menu_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
